# your domain
domain: doudoubing3332.heroku.com

# database url
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files: 
  # use local file
  - ./config/source.yaml
  # use web file
  - https://doudoubing3332.heroku.com/source.yaml
