# 爬订阅链接

- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/oouxx/fqsub/master/sub.list
- type: webfuzzsub
  options:
    url: https://github.com/doudoubinga/ceshi/blob/master/trash/base64-sub
- type: webfuzzsub
  options:
    url: https://github.com/JACKUSR2089/v2ray-subscribed   
- type: webfuzzsub
  options:
    url: https://github.com/pojiezhiyuanjun/freev2
    





# 爬节点
- type: webfuzz
  options:
    url: https://telegra.ph/2020-10-3-10-02
- type: webfuzz
  options:
    url: https://lisondawang.tk/jiedianfenxiang.html









# tg订阅+节点

- type: tgchannel
  options:
    channel: NetfreexSrV
    num: 200
- type: tgchannel
  options:
    channel: V2List
    num: 200
- type: tgchannel
  options:
    channel: ssrList
    num: 200
- type: tgchannel
  options:
    channel: SSRSUB
    num: 200
- type: tgchannel
  options:
    channel: FreeSSRNode
    num: 200
- type: tgchannel
  options:
    channel: V2List
    num: 200
- type: tgchannel
  options:
    channel: ssrtool
    num: 200
- type: tgchannel
  options:
    channel: freeshadowsock
    num: 200
- type: tgchannel
  options:
    channel: jiedianfenxiang
    num: 200
- type: tgchannel
  options:
    channel: fanqiang666
    num: 200
- type: tgchannel
  options:
    channel: ssrtool_crack
    num: 200
- type: tgchannel
  options:
    channel: ssrshares
    num: 200
- type: tgchannel
  options:
    channel: gongyijichangfenxiang
    num: 200
- type: tgchannel
  options:
    channel: fanqiang666
    num: 200
- type: tgchannel
  options:
    channel: ssrtool_crack
    num: 200
- type: tgchannel
  options:
    channel: moneyfly01
    num: 200
- type: tgchannel
  options:
    channel: ssrv2taytgshare
    num: 200

- type: tgchannel
  options:
    channel: freeshadowsock
    num: 200
- type: tgchannel
  options:
    channel: gyjclub
    num: 200
- type: tgchannel
  options:
    channel: TgProxies
    num: 200
- type: tgchannel
  options:
    channel: VPNFolder
    num: 200
- type: tgchannel
  options:
    channel: vmesssr
    num: 200
- type: tgchannel
  options:
    channel: youmtp
    num: 200
- type: tgchannel
  options:
    channel: ssrkn
    num: 200
- type: tgchannel
  options:
    channel: abchz
    num: 200
- type: tgchannel
  options:
    channel: yg251153
    num: 200
- type: tgchannel
  options:
    channel: woyaofq
    num: 200
- type: tgchannel
  options:
    channel: wwx_com
    num: 200
- type: tgchannel
  options:
    channel: freessr4k
    num: 200
- type: tgchannel
  options:
    channel: ultrafreevpn
    num: 200
- type: tgchannel
  options:
    channel: VSshit
    num: 200
- type: tgchannel
  options:
    channel: InternetSSR
    num: 200
- type: tgchannel
  options:
    channel: baipiaodadui
    num: 200
- type: tgchannel
  options:
    channel: mtproxy666
    num: 200
- type: tgchannel
  options:
    channel: v2ray666
    num: 200



# 论坛
#- type: web-fanqiangdang
#  options:
#    url: https://fanqiangdang.com/forum-48-1.html

# 网站抓取
- type: web-freessrxyz
  options:

# 爬订阅

#- type: subscribe
#  options:
#    url: https://gooii.ml/v2ray/sub/vmess.html






  
  
  
